project/App/urls.py
from django.urls import path

app_name = 'App'

from . import views

urlpatterns = [
   path('', views.home, name='home'),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include

# from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('App/', include('App.urls')),
    path('producto/', include('producto.urls')),
]

project/core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from . import views

app_name = "core"


urlpatterns = [
    path("", views.home, name="home"),
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("register/", views.register, name="register"),
    path("logout/", LogoutView.as_view(template_name="core/logout.html"), name="logout"),
    path("contacto/", views.contacto, name="contacto"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns += staticfiles_urlpatterns()

project/producto/urls.py
from django.urls import path

from . import views

app_name = "producto"

# ProductoCategoria
urlpatterns = [
    path("", views.home, name="home"),
    # path("productocategoria/create/", views.productocategoria_create, name="productocategoria_create"),
    path("productocategoria/create/", views.ProductoCategoriaCreate.as_view(), name="productocategoria_create"),
    # path("productocategoria/list/", views.productocategoria_list, name="productocategoria_list"),
    path("productocategoria/list/", views.ProductoCategoriaList.as_view(), name="productocategoria_list"),
    # path("productocategoria/detail/<int:pk>", views.productocategoria_detail, name="productocategoria_detail"),
    path("productocategoria/detail/<int:pk>", views.ProductoCategoriaDetail.as_view(), name="productocategoria_detail"),
    # path("productocategoria/update/<int:pk>", views.productocategoria_update, name="productocategoria_update"),
    path("productocategoria/update/<int:pk>", views.ProductoCategoriaUpdate.as_view(), name="productocategoria_update"),
    # path("productocategoria/delete/<int:pk>", views.productocategoria_delete, name="productocategoria_delete"),
    path("productocategoria/delete/<int:pk>", views.ProductoCategoriaDelete.as_view(), name="productocategoria_delete"),
]

# Producto
urlpatterns += [
    path("producto/list/", views.ProductoList.as_view(), name="producto_list"),
    path("producto/create/", views.ProductoCreate.as_view(), name="producto_create"),
    path("producto/detail/<int:pk>", views.ProductoDetail.as_view(), name="producto_detail"),
    path("producto/update/<int:pk>", views.ProductoUpdate.as_view(), name="producto_update"),
    path("producto/delete/<int:pk>", views.ProductoDelete.as_view(), name="producto_delete"),
]

project/producto/models.py
from django.db import models
from django.utils import timezone


class ProductoCategoria(models.Model):
    """Categorías de productos"""

    nombre = models.CharField(max_length=200, unique=True)
    descripcion = models.CharField(max_length=250, null=True, blank=True, verbose_name="descripción")

    def __str__(self) -> str:
        """Representa una instancia del modelo como una cadena de texto"""
        return self.nombre

    class Meta:
        verbose_name = "categoría de productos"
        verbose_name_plural = "categorías de productos"


class Producto(models.Model):
    categoria_id = models.ForeignKey(
        ProductoCategoria, null=True, blank=True, on_delete=models.SET_NULL, verbose_name="categoría de producto"
    )
    nombre = models.CharField(max_length=100)
    unidad_medida = models.CharField(max_length=100)
    cantidad = models.FloatField()
    precio = models.FloatField()
    descripcion = models.TextField(null=True, blank=True, verbose_name="descripción")
    fecha_actualizacion = models.DateField(
        null=True, blank=True, default=timezone.now, editable=False, verbose_name="fecha de actualización"
    )

    def __str__(self) -> str:
        return f"{self.nombre} ({self.unidad_medida}) ${self.precio:.2f}"

    class Meta:
        verbose_name = "producto"
        verbose_name_plural = "productos"

project/producto/forms.py
from django import forms

from . import models

# class ProductoCategoriaForm(forms.Form):
#     nombre = forms.CharField()
#     descripcion = forms.CharField()


class ProductoCategoriaForm(forms.ModelForm):
    class Meta:
        model = models.ProductoCategoria
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
        }


class ProductoForm(forms.ModelForm):
    class Meta:
        model = models.Producto
        fields = "__all__"
        widgets = {
            "nombre": forms.TextInput(attrs={"class": "form-control"}),
            "descripcion": forms.TextInput(attrs={"class": "form-control"}),
            "unidad_medida": forms.TextInput(attrs={"class": "form-control"}),
            "precio": forms.TextInput(attrs={"class": "form-control"}),
            "categoria_id": forms.Select(attrs={"class": "form-control"}),
            "fecha_actualizacion": forms.TextInput(attrs={"class": "form-control"}),
        }

project/producto/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.db.models.query import QuerySet
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView,
)

from . import forms, models


def home(request):
    return render(request, "producto/index.html")


# *** PRODUCTOCATEOGORIA

# LIST
# def productocategoria_list(request):
#     consulta = request.GET.get("consulta", None)
#     if consulta:
#         print(consulta)
#         query = models.ProductoCategoria.objects.filter(nombre__icontains=consulta)
#     else:
#         query = models.ProductoCategoria.objects.all()
#     context = {"productos": query}
#     return render(request, "producto/productocategoria_list.html", context)


class ProductoCategoriaList(ListView):
    model = models.ProductoCategoria

    # context_object_name = "productos"
    # template_name = "producto/productocategoria___list.html"

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.ProductoCategoria.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.ProductoCategoria.objects.all()
        return object_list

    # def get_queryset(self):
    #     queryset = super().get_queryset()
    #     consulta = self.request.GET.get("consulta")
    #     if consulta:
    #         queryset = queryset.filter(Q(nombre__icontains=consulta) | Q(descripcion__icontains=consulta))
    #     return queryset


# CREATE
# def productocategoria_create(request):
#     if request.method == "POST":
#         form = forms.ProductoCategoriaForm(request.POST)
#         if form.is_valid:
#             form.save()
#             return redirect("producto:home")
#     else:  # request.method == "GET"
#         form = forms.ProductoCategoriaForm()
#     return render(request, "producto/productocategoria_create.html", context={"form": form})


class ProductoCategoriaCreate(CreateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    success_url = reverse_lazy("producto:home")


# UPDATE
# def productocategoria_update(request, pk: int):
#     query = models.ProductoCategoria.objects.get(id=pk)
#     if request.method == "POST":
#         form = forms.ProductoCategoriaForm(request.POST, instance=query)
#         if form.is_valid:
#             form.save()
#             return redirect("producto:productocategoria_list")
#     else:  # request.method == "GET"
#         form = forms.ProductoCategoriaForm(instance=query)
#     return render(request, "producto/productocategoria_update.html", context={"form": form})


class ProductoCategoriaUpdate(UpdateView):
    model = models.ProductoCategoria
    form_class = forms.ProductoCategoriaForm
    success_url = reverse_lazy("producto:productocategoria_list")


# DETAIL
# def productocategoria_detail(request, pk: int):
#     query = models.ProductoCategoria.objects.get(id=pk)
#     return render(request, "producto/productocategoria_detail.html", {"producto": query})


class ProductoCategoriaDetail(DetailView):
    model = models.ProductoCategoria
    # context_object_name = "producto"


# DELETE
# def productocategoria_delete(request, pk: int):
#     query = models.ProductoCategoria.objects.get(id=pk)
#     if request.method == "POST":
#         query.delete()
#         return redirect("producto:productocategoria_list")
#     return render(request, "producto/productocategoria_delete.html", context={"producto": query})


class ProductoCategoriaDelete(LoginRequiredMixin, DeleteView):
    model = models.ProductoCategoria
    # template_name = "producto/productocategoria_delete.html"
    success_url = reverse_lazy("producto:productocategoria_list")


# *** PRODUCTO


class ProductoList(ListView):
    model = models.Producto

    def get_queryset(self) -> QuerySet:
        if self.request.GET.get("consulta"):
            consulta = self.request.GET.get("consulta")
            object_list = models.Producto.objects.filter(nombre__icontains=consulta)
        else:
            object_list = models.Producto.objects.all()
        return object_list


class ProductoCreate(CreateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:home")


class ProductoUpdate(UpdateView):
    model = models.Producto
    form_class = forms.ProductoForm
    success_url = reverse_lazy("producto:producto_list")


class ProductoDetail(DetailView):
    model = models.Producto


class ProductoDelete(LoginRequiredMixin, DeleteView):
    model = models.Producto
    success_url = reverse_lazy("producto:producto_list")

project/producto/templates/producto/index.html
{% extends 'core/base.html' %}
{% block titulo %}
    App Tienda
{% endblock titulo %}
{% block contenido %}
<div class="container my-5">
    <h3 class="pb-3 border-bottom">Categoría de tienda</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-primary me-md-2" href="{% url 'producto:productocategoria_create' %}" role="button">Crear Categorías tienda</a>
        <a class="btn btn-outline-primary" href="{% url 'producto:productocategoria_list' %}" role="button">Listar Categorías tienda</a>
    </div>

    <h3 class="pb-3 border-bottom">Tienda</h3>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-success me-md-2" href="{% url 'producto:producto_create' %}" role="button">Crear Articulos</a>
        <a class="btn btn-outline-success" href="{% url 'producto:producto_list' %}" role="button">Listar Articulos</a>
    </div>

    <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4">
        <a class="btn btn-secondary" href="{% url 'core:home' %}" role="button">Volver a Inicio</a>
    </div>
</div>

{% endblock contenido %}

project/producto/templates/producto/producto_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Productos: Borrar un Producto
{% endblock titulo %}

{% block contenido %}
    
    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/producto_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
    Productos: Detalle de un Producto
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ object.nombre }}</li>
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'producto:producto_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/producto_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Producto: 
    {% if form.instance.pk %}
        Editar
    {% else %}
        Crear
    {% endif %}
    Productos
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/producto_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    Productos: Lista de Productos
{% endblock titulo %}
{% block contenido %}
    <div class="container my-5">
        <div class="py-4">
            <form class="input-group mb-3"
                  action="{% url 'producto:producto_list' %}"
                  method="get">
                <input type="text"
                       class="form-control"
                       name="consulta"
                       placeholder="Buscar..."
                       aria-label="Buscar">
                <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Buscar</button>
            </form>
        </div>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Producto</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for producto in object_list %}
                    <tr>
                        <td>{{ producto.nombre }}</td>
                        <td>
                            <a class="btn btn-info btn-sm me-1"
                               href="{% url 'producto:producto_detail' producto.id %}">Detalle</a>
                            <a class="btn btn-warning btn-sm me-1"
                               href="{% url 'producto:producto_update' producto.id %}">Cambiar</a>
                            <a class="btn btn-danger btn-sm"
                               href="{% url 'producto:producto_delete' producto.id %}">Borrar</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="mt-4">
            <a class="btn btn-secondary"
               href="{% url 'producto:home' %}"
               role="button">Volver al inicio de Producto</a>
        </div>
    </div>
{% endblock contenido %}

project/producto/templates/producto/productocategoria_confirm_delete.html
{% extends 'core/base.html' %}

{% block titulo %}
    Productos: Borrar una Categoría de Productos
{% endblock titulo %}

{% block contenido %}
    
    <p class="fs-5 fst-italic">¿Confirma eliminar "{{ object.nombre }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Confirmar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/productocategoria_detail.html
{% extends 'core/base.html' %}
{% block titulo %}
    Productos: Detalle de una Categoría de Producto
{% endblock titulo %}

{% block contenido %}

    <ul>
        <li>Nombre: {{ object.nombre }}</li>
        <li>Descripción: {{ object.descripcion }}</li>
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'producto:productocategoria_list' %}">Volver</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/productocategoria_form.html
{% extends 'core/base.html' %}

{% block titulo %}
    Producto: 
    {% if form.instance.pk %}
        Editar
    {% else %}
        Crear
    {% endif %}
    Categoría de Productos
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/productocategoria_list.html
{% extends 'core/base.html' %}
{% block titulo %}
    Productos: Lista de Categoría de Productos
{% endblock titulo %}

{% block contenido %}

    <div class="py-lg-4 ">
        <form action="{% url 'producto:productocategoria_list' %}" method="get">
            <input type="text" name="consulta" placeholder="Buscar...">
        </form>
    </div>
    <ul>
        {% comment  %}
        {% for producto in productos %}
        {% endcomment %}

        {% for producto in object_list %}
            <li>{{ producto.nombre }}
                <a href="{% url 'producto:productocategoria_detail' producto.id %}">Detalle</a>
                <a href="{% url 'producto:productocategoria_update' producto.id %}">Cambiar</a>
                <a href="{% url 'producto:productocategoria_delete' producto.id %}">Borrar</a>
            </li>
        {% endfor %}
    </ul>

    <div class="fs-3 pb-4">
        <a href="{% url 'producto:home' %}">Volver al inicio de Producto</a>
    </div>

{% endblock contenido %}

project/producto/templates/producto/productocategoria_update.html
{% extends 'core/base.html' %}

{% block titulo %}
    Productos: Cambiar una Categoría de Productos
{% endblock titulo %}

{% block contenido %}
    
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
    <div class="fs-3 pb-4">
        <a href="{% url 'producto:productocategoria_list' %}">Volver</a>
    </div>

{% endblock contenido %}